package com.scripto.backend.classification.domain;

public enum FallbackReason {
    LOCAL_MODEL_DISABLED,
    LOCAL_MODEL_ERROR,
    INVALID_EMBEDDING,
    UNSUPPORTED_CATEGORY,
    OTHER_REQUIRES_FALLBACK,
    LOW_CATEGORY_CONFIDENCE,
    OUT_OF_DISTRIBUTION,
    LOW_DIFFICULTY_CONFIDENCE,
    NO_VALID_TAGS,
    INVALID_LOCAL_OUTPUT,
    EXTERNAL_AI_NOT_ALLOWED
}
